### ISSUE TITLE
Getting User Data

### ISSUE THREAD

**Issue by artdude543** [WatchBeam/beam-client-node#3]
Any chance we could have getUser() back? Was a really handy function to have allowing us easy access to the user data.

**Comment by connor4312** [comment]
A user service with a getUser method could be made, but a getUser on the client doesn't really fit anymore. It was there for convenience since the login endpoint returned user data, but OAuth has its own set of requests and responses which don't contain such details.

Therefore it doesn't make sense to have that data globally available like it was before; it's no longer a global resource.
